spring.datasource.url=jdbc:mysql://localhost:3306/wellness_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8080
jwt.secret=mysupersecretkeyformyjwt12345678901234567890
jwt.expiration=31536000000
google.calendar.client-id=532314399750-sa1hpcscljqsjfh773cmolamh0lrjh6o.apps.googleusercontent.com
google.calendar.client-secret=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
google.calendar.redirect-uri=http://localhost:8080/oauth2/callback/google
spring.sql.init.mode=always
openfda.base-url=https://api.fda.gov
openfda.api-key=3m53aMBYJqGn4WxSY7BGgb7MbCh8JkxK05bQJ73
